# Generated by Django 4.0.2 on 2022-02-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_print'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print',
            old_name='image',
            new_name='img',
        ),
    ]
