# Generated by Django 4.0.2 on 2022-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_image_print_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='verified_print',
            field=models.BooleanField(default=False),
        ),
    ]
